FROM ubuntu:18.04

MAINTAINER Mingxun Wang "mwang87@gmail.com"

RUN apt-get update -y
RUN apt-get install -y python3-pip python3 build-essential

RUN pip3 install ftputil
RUN pip3 install flask
RUN pip3 install gunicorn
RUN pip3 install requests
RUN pip3 install celery
RUN pip3 install joblib
RUN pip3 install vladiate
RUN pip3 install pandas

COPY . /app
WORKDIR /app