FROM continuumio/miniconda3:latest
MAINTAINER Mingxun Wang "mwang87@gmail.com"

WORKDIR /app
RUN apt-get update -y
RUN conda install -c anaconda flask
RUN conda install -c conda-forge celery
RUN conda install -c qiime2 qiime2
  

COPY . /app
WORKDIR /app

